---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"

platforms:
  - name: gsdev/centos-6-7-minimal-chef-12-6-0
    driver_config:
      platform: rhel

suites:
  - name: default
    run_list:
      - recipe[solr::default]
    attributes:
