---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[solr::default]
    attributes:
